#!/bin/sh
set -e

chmod 755 /usr/share/quake3/ioquake3
chmod 755 /usr/bin/quake3

if [ -x /usr/bin/gtk-update-icon-cache ]; then
    gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
fi

if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q /usr/share/applications || true
fi
