#!/bin/sh
set -e
chmod 755 /usr/bin/classic-cube /usr/local/games/classic-cube/ClassiCube
chown -R gamercard:gamercard /usr/local/games/classic-cube
update-desktop-database -q /usr/share/applications
exit 0
