#!/bin/sh
set -e

chmod 755 /usr/bin/vaixterm /usr/lib/vaixterm/vaixterm

if [ -x /usr/bin/update-desktop-database ]; then
    update-desktop-database -q /usr/share/applications
fi

if [ -x /usr/bin/gtk-update-icon-cache ]; then
    gtk-update-icon-cache -f -t /usr/share/icons/hicolor || true
fi

sync

exit 0
